(function(){'use strict';const D=window.ICON_COMPACT7_DATA,K='zircon.icon-review.sitewide-png-compact-07.v1',S=load();const list=document.getElementById('review-list'),globalNote=document.getElementById('global-note');
function load(){try{const v=JSON.parse(localStorage.getItem(K)||'{}');return v&&typeof v==='object'?v:{}}catch(_){return{}}}function save(){localStorage.setItem(K,JSON.stringify(S));progress()}function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function src(c){return`assets/png/${c.slug}.png`}
function locked(){document.getElementById('locked-grid').innerHTML=D.locked.map(i=>`<div class="locked-item"><img src="${i.src}" alt="" width="31" height="31"><strong>${esc(i.name)}</strong><span>${esc(i.decision)}</span></div>`).join('')}
function sizes(c){return`<div class="sizes">${[28,32,48].map(n=>`<div class="size"><img src="${src(c)}" alt="" width="${n}" height="${n}"><small>${n}px</small></div>`).join('')}</div>`}
function card(i){const s=S[i.id]||{},cls=s.decision?(s.decision==='reject'?' is-reject':' is-selected'):'';const choices=i.choices.map(c=>`<label class="choice"><input type="radio" name="${esc(i.id)}" value="${c.id}" ${s.decision===c.id?'checked':''}><div class="choice-surface"><div class="choice-title"><strong>${esc(c.label)}</strong><span class="letter">${c.id}</span></div>${sizes(c)}<p class="choice-desc">${esc(c.desc)}</p></div></label>`).join('');return`<article class="review-card${cls}" data-id="${esc(i.id)}"><header class="card-head"><div><p class="eyebrow">${esc(i.id)}</p><h3>${esc(i.name)}</h3></div><span class="rev">revision 7</span></header><p class="feedback-note">当前状态：${esc(i.feedback)}</p><div class="choice-grid">${choices}</div><div class="item-foot"><label><input type="radio" name="${esc(i.id)}" value="reject" ${s.decision==='reject'?'checked':''}><span>三套全部打回</span></label><textarea data-note="${esc(i.id)}" placeholder="如仍需修改，请写明希望保留或推翻什么……">${esc(s.note||'')}</textarea></div></article>`}
function render(){list.innerHTML=D.items.map(card).join('');list.querySelectorAll('input[type=radio]').forEach(x=>x.addEventListener('change',()=>{S[x.name]=S[x.name]||{};S[x.name].decision=x.value;x.closest('.review-card').className='review-card '+(x.value==='reject'?'is-reject':'is-selected');save()}));list.querySelectorAll('[data-note]').forEach(x=>x.addEventListener('input',()=>{S[x.dataset.note]=S[x.dataset.note]||{};S[x.dataset.note].note=x.value;save()}))}
function progress(){const n=D.items.filter(i=>S[i.id]?.decision).length;document.getElementById('done-count').textContent=n;document.getElementById('progress-fill').style.width=`${n/D.items.length*100}%`}
function obj(){return{format:D.format,batch:D.batch,revision:D.revision,audited_commit:D.auditedCommit,exported_at:new Date().toISOString(),global_note:globalNote.value.trim(),architecture:D.architecture,locked:D.locked.map(i=>({id:i.id,decision:i.decision})),scenes:D.items.map(i=>({id:i.id,revision:7,category:'toolbox',decision:S[i.id]?.decision||'unreviewed',note:(S[i.id]?.note||'').trim()}))}}function text(){const p=obj(),a=[p.format,`batch=${p.batch}`,`revision=${p.revision}`,`audited_commit=${p.audited_commit}`,`exported_at=${p.exported_at}`,`global_note=${p.global_note||'(none)'}`,'',`ARCHITECTURE [${p.architecture.id}] decision=${p.architecture.decision}`,'','LOCKED'];p.locked.forEach(i=>a.push(`[${i.id}] decision=${i.decision}`));a.push('');p.scenes.forEach(s=>a.push(`[${s.id}] revision=7 category=toolbox decision=${s.decision}`,`note=${s.note||'(none)'}`,''));return a.join('\n')}
async function copy(){const t=text();try{await navigator.clipboard.writeText(t)}catch(_){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}document.getElementById('export-status').textContent='已复制，直接粘贴回 Codex 即可。'}function download(){const b=new Blob([JSON.stringify(obj(),null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`icon-review-${D.batch}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);document.getElementById('export-status').textContent='JSON 文件已下载。'}
globalNote.value=S.__globalNote||'';globalNote.addEventListener('input',()=>{S.__globalNote=globalNote.value;save()});document.getElementById('copy-export').addEventListener('click',copy);document.getElementById('download-export').addEventListener('click',download);document.getElementById('preview-export').addEventListener('click',()=>{const p=document.getElementById('export-preview');p.textContent=text();p.hidden=!p.hidden;if(!p.hidden)p.scrollIntoView({behavior:'smooth',block:'nearest'})});locked();render();progress();}());
