(function(){'use strict';
const D=window.ICON_COMPACT_DATA,K='zircon.icon-review.sitewide-png-compact-03.v1',S=load();let F='all';
const list=document.getElementById('review-list'),globalNote=document.getElementById('global-note');
function load(){try{const v=JSON.parse(localStorage.getItem(K)||'{}');return v&&typeof v==='object'?v:{}}catch(_){return{}}}
function save(){localStorage.setItem(K,JSON.stringify(S));progress()}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function compact(i){return `assets/png/${i.slug}.png`}
function detailed(i){return `../refine-02/assets/thumbs/${i.slug}.png`}
function family(){document.getElementById('family-grid').innerHTML=D.items.map(i=>`<a class="family-item" href="#${esc(i.id)}"><img src="${compact(i)}" alt="" width="32" height="32"><span>${esc(i.name)}</span></a>`).join('')}
function sizes(src,label){return `<div class="sizes">${[28,32,48].map(n=>`<div class="size"><img src="${src}" alt="" width="${n}" height="${n}"><small>${n}px</small></div>`).join('')}</div>`}
function card(i){const s=S[i.id]||{},c=s.decision?` is-${s.decision}`:'';return `<article class="review-card${c}" id="${esc(i.id)}" data-id="${esc(i.id)}"><header class="card-head"><div><p class="eyebrow">${esc(i.id)}</p><h3>${esc(i.name)}</h3><p>${esc(i.change)}</p></div><span class="rev">revision 3</span></header><div class="compare"><section class="variant"><h4>Detailed <span>第二轮已批准母版</span></h4>${sizes(detailed(i),'Detailed')}</section><section class="variant"><h4>Compact <span>本轮光学小尺寸版</span></h4>${sizes(compact(i),'Compact')}</section></div><div class="decision"><label><input type="radio" name="${esc(i.id)}" value="compact" ${s.decision==='compact'?'checked':''}><span>小卡采用 Compact</span></label><label><input type="radio" name="${esc(i.id)}" value="detailed" ${s.decision==='detailed'?'checked':''}><span>小卡仍用 Detailed</span></label><label><input type="radio" name="${esc(i.id)}" value="revise" ${s.decision==='revise'?'checked':''}><span>Compact 仍需修改</span></label></div><footer class="card-foot"><textarea data-note="${esc(i.id)}" placeholder="如需修改，请说明在 28–32px 下哪里仍不够直观……">${esc(s.note||'')}</textarea></footer></article>`}
function render(){list.innerHTML=D.items.map(card).join('');list.querySelectorAll('input[type=radio]').forEach(x=>x.addEventListener('change',()=>{S[x.name]=S[x.name]||{};S[x.name].decision=x.value;save();const c=x.closest('.review-card');c.className='review-card is-'+x.value;apply()}));list.querySelectorAll('[data-note]').forEach(x=>x.addEventListener('input',()=>{S[x.dataset.note]=S[x.dataset.note]||{};S[x.dataset.note].note=x.value;save()}));apply();progress()}
function progress(){const n=D.items.filter(i=>S[i.id]&&S[i.id].decision).length;document.getElementById('done-count').textContent=n;document.getElementById('progress-fill').style.width=`${n/D.items.length*100}%`}
function apply(){let n=0;list.querySelectorAll('.review-card').forEach(c=>{const d=S[c.dataset.id]&&S[c.dataset.id].decision,show=F==='all'||(F==='unreviewed'?!d:d===F);c.hidden=!show;if(show)n++});document.getElementById('empty').hidden=n!==0}
function obj(){return{format:D.format,batch:D.batch,revision:D.revision,audited_commit:D.auditedCommit,exported_at:new Date().toISOString(),global_note:globalNote.value.trim(),detailed_masters:'approved in sitewide-png-refine-02',scenes:D.items.map(i=>({id:i.id,revision:3,category:'toolbox',decision:S[i.id]?.decision||'unreviewed',note:(S[i.id]?.note||'').trim()}))}}
function text(){const p=obj(),a=[p.format,`batch=${p.batch}`,`revision=${p.revision}`,`audited_commit=${p.audited_commit}`,`exported_at=${p.exported_at}`,`global_note=${p.global_note||'(none)'}`,`detailed_masters=${p.detailed_masters}`,''];p.scenes.forEach(s=>a.push(`[${s.id}] revision=3 category=toolbox decision=${s.decision}`,`note=${s.note||'(none)'}`,''));return a.join('\n')}
async function copy(){const t=text();try{await navigator.clipboard.writeText(t)}catch(_){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}document.getElementById('export-status').textContent='已复制，直接粘贴回 Codex 即可。'}
function download(){const b=new Blob([JSON.stringify(obj(),null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`icon-review-${D.batch}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);document.getElementById('export-status').textContent='JSON 文件已下载。'}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{F=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===b));apply()}));document.getElementById('compact-all').addEventListener('click',()=>{D.items.forEach(i=>{S[i.id]=S[i.id]||{};S[i.id].decision='compact'});save();render()});globalNote.value=S.__globalNote||'';globalNote.addEventListener('input',()=>{S.__globalNote=globalNote.value;save()});document.getElementById('copy-export').addEventListener('click',copy);document.getElementById('download-export').addEventListener('click',download);document.getElementById('preview-export').addEventListener('click',()=>{const p=document.getElementById('export-preview');p.textContent=text();p.hidden=!p.hidden;if(!p.hidden)p.scrollIntoView({behavior:'smooth',block:'nearest'})});family();render();
}());
