(function(){'use strict';const D=window.ICON_COMPACT4_DATA,K='zircon.icon-review.sitewide-png-compact-04.v1',S=load();let F='all';const list=document.getElementById('review-list'),globalNote=document.getElementById('global-note');
function load(){try{const v=JSON.parse(localStorage.getItem(K)||'{}');return v&&typeof v==='object'?v:{}}catch(_){return{}}}function save(){localStorage.setItem(K,JSON.stringify(S));progress()}function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function old(i){return`../compact-03/assets/png/${i.slug}.png`}function fresh(i){return`assets/png/${i.slug}.png`}
function family(){const rows=D.locked.map(i=>({...i,src:old(i),locked:true})).concat(D.items.map(i=>({...i,src:fresh(i),locked:false})));document.getElementById('family-grid').innerHTML=rows.map(i=>`<a class="family-item${i.locked?' is-locked':''}" href="${i.locked?'#locked-title':'#'+esc(i.id)}"><img src="${i.src}" alt="" width="32" height="32"><span>${esc(i.name)}</span>${i.locked?'<em>已锁定</em>':''}</a>`).join('')}
function locked(){document.getElementById('locked-grid').innerHTML=D.locked.map(i=>`<div class="locked-item"><img src="${old(i)}" alt="" width="40" height="40"><div><strong>${esc(i.name)}</strong><span>第三轮 Compact 已批准</span></div></div>`).join('')}
function sizes(src){return`<div class="sizes">${[28,32,48].map(n=>`<div class="size"><img src="${src}" alt="" width="${n}" height="${n}"><small>${n}px</small></div>`).join('')}</div>`}
function card(i){const s=S[i.id]||{},c=s.decision?` is-${s.decision}`:'';return`<article class="review-card${c}" id="${esc(i.id)}" data-id="${esc(i.id)}"><header class="card-head"><div><p class="eyebrow">${esc(i.id)}</p><h3>${esc(i.name)}</h3><p>${esc(i.change)}</p></div><span class="rev">revision 4</span></header><p class="feedback-note">你的第三轮批注：${esc(i.feedback)}</p><div class="compare"><section class="variant old-variant"><h4>Compact r3 <span>被打回旧版</span></h4>${sizes(old(i))}</section><section class="variant new"><h4>Revision 4 <span>本轮直观版</span></h4>${sizes(fresh(i))}</section></div><div class="decision"><label><input type="radio" name="${esc(i.id)}" value="approve" ${s.decision==='approve'?'checked':''}><span>批准 revision 4</span></label><label><input type="radio" name="${esc(i.id)}" value="revise" ${s.decision==='revise'?'checked':''}><span>仍需修改</span></label></div><footer class="card-foot"><textarea data-note="${esc(i.id)}" placeholder="如仍需修改，请说明哪个主物件或轮廓还不够直观……">${esc(s.note||'')}</textarea></footer></article>`}
function render(){list.innerHTML=D.items.map(card).join('');list.querySelectorAll('input[type=radio]').forEach(x=>x.addEventListener('change',()=>{S[x.name]=S[x.name]||{};S[x.name].decision=x.value;save();x.closest('.review-card').className='review-card is-'+x.value;apply()}));list.querySelectorAll('[data-note]').forEach(x=>x.addEventListener('input',()=>{S[x.dataset.note]=S[x.dataset.note]||{};S[x.dataset.note].note=x.value;save()}));apply();progress()}
function progress(){const n=D.items.filter(i=>S[i.id]?.decision).length;document.getElementById('done-count').textContent=n;document.getElementById('progress-fill').style.width=`${n/D.items.length*100}%`}function apply(){let n=0;list.querySelectorAll('.review-card').forEach(c=>{const d=S[c.dataset.id]?.decision,show=F==='all'||(F==='unreviewed'?!d:d===F);c.hidden=!show;if(show)n++});document.getElementById('empty').hidden=n!==0}
function obj(){return{format:D.format,batch:D.batch,revision:D.revision,audited_commit:D.auditedCommit,exported_at:new Date().toISOString(),global_note:globalNote.value.trim(),locked:D.locked.map(i=>({id:i.id,decision:'compact-r3'})),scenes:D.items.map(i=>({id:i.id,revision:4,category:'toolbox',decision:S[i.id]?.decision||'unreviewed',note:(S[i.id]?.note||'').trim()}))}}function text(){const p=obj(),a=[p.format,`batch=${p.batch}`,`revision=${p.revision}`,`audited_commit=${p.audited_commit}`,`exported_at=${p.exported_at}`,`global_note=${p.global_note||'(none)'}`,'','LOCKED'];p.locked.forEach(i=>a.push(`[${i.id}] decision=${i.decision}`));a.push('');p.scenes.forEach(s=>a.push(`[${s.id}] revision=4 category=toolbox decision=${s.decision}`,`note=${s.note||'(none)'}`,''));return a.join('\n')}
async function copy(){const t=text();try{await navigator.clipboard.writeText(t)}catch(_){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}document.getElementById('export-status').textContent='已复制，直接粘贴回 Codex 即可。'}function download(){const b=new Blob([JSON.stringify(obj(),null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`icon-review-${D.batch}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);document.getElementById('export-status').textContent='JSON 文件已下载。'}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{F=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===b));apply()}));document.getElementById('approve-all').addEventListener('click',()=>{D.items.forEach(i=>{S[i.id]=S[i.id]||{};S[i.id].decision='approve'});save();render()});globalNote.value=S.__globalNote||'';globalNote.addEventListener('input',()=>{S.__globalNote=globalNote.value;save()});document.getElementById('copy-export').addEventListener('click',copy);document.getElementById('download-export').addEventListener('click',download);document.getElementById('preview-export').addEventListener('click',()=>{const p=document.getElementById('export-preview');p.textContent=text();p.hidden=!p.hidden;if(!p.hidden)p.scrollIntoView({behavior:'smooth',block:'nearest'})});family();locked();render();}());
